name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  shop:
    aliases: ["fdyshop"]
    description: "BUY>>?? what do you expect"
  test:
    aliases: ["ts"]
    description: "test lol"
depend: [Essentials]