name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  shop:
    aliases: ["fdyshop"]
    description: "BUY>>?? what do you expect"
  balance:
    aliases: ["bal"]
    description: "check ur money"
depend: [Essentials]